export const CLIENTS = [
  {
    id: 1,
    avatar: false,
    "first-name": "Emma",
    "last-name": "Jansen",
    "start-date": "2025-01-12",
    "current-program": "Rehab A",
    compliance: 92,
    trainer: "Mark",
  },
  {
    id: 2,
    avatar: false,
    "first-name": "Lars",
    "last-name": "De Vries",
    "start-date": "2025-01-15",
    "current-program": "Strength Basic",
    compliance: 85,
    trainer: "Sophie",
  },
  {
    id: 3,
    avatar: false,
    "first-name": "Mila",
    "last-name": "Bakker",
    "start-date": "2025-01-20",
    "current-program": "Mobility Intro",
    compliance: 60,
    trainer: "Tom",
  },
  {
    id: 4,
    avatar: false,
    "first-name": "Noah",
    "last-name": "Bos",
    "start-date": "2025-01-23",
    "current-program": "Strength Advanced",
    compliance: 88,
    trainer: "Sophie",
  },
  {
    id: 5,
    avatar: false,
    "first-name": "Julia",
    "last-name": "Visser",
    "start-date": "2025-01-25",
    "current-program": "Rehab B",
    compliance: 95,
    trainer: "Mark",
  },
  {
    id: 6,
    avatar: false,
    "first-name": "Finn",
    "last-name": "Hendriks",
    "start-date": "2025-01-28",
    "current-program": "Cardio Boost",
    compliance: 43,
    trainer: "Lisa",
  },
  {
    id: 7,
    avatar: false,
    "first-name": "Sofie",
    "last-name": "Mulder",
    "start-date": "2025-02-01",
    "current-program": "Strength Basic",
    compliance: 73,
    trainer: "Tom",
  },
  {
    id: 8,
    avatar: false,
    "first-name": "Daan",
    "last-name": "Dekker",
    "start-date": "2025-02-03",
    "current-program": "Mobility Intro",
    compliance: 55,
    trainer: "Sophie",
  },
  {
    id: 9,
    avatar: false,
    "first-name": "Lotte",
    "last-name": "Smit",
    "start-date": "2025-02-04",
    "current-program": "Rehab A",
    compliance: 90,
    trainer: "Lisa",
  },
  {
    id: 10,
    avatar: false,
    "first-name": "Bram",
    "last-name": "Meijer",
    "start-date": "2025-02-06",
    "current-program": "Strength Advanced",
    compliance: 79,
    trainer: "Mark",
  },
  {
    id: 11,
    avatar: false,
    "first-name": "Nina",
    "last-name": "Koning",
    "start-date": "2025-02-08",
    "current-program": "Cardio Boost",
    compliance: 82,
    trainer: "Tom",
  },
  {
    id: 12,
    avatar: false,
    "first-name": "Timo",
    "last-name": "Martens",
    "start-date": "2025-02-09",
    "current-program": "Rehab C",
    compliance: 91,
    trainer: "Lisa",
  },
  {
    id: 13,
    avatar: false,
    "first-name": "Eva",
    "last-name": "Hoekstra",
    "start-date": "2025-02-11",
    "current-program": "Mobility Advanced",
    compliance: 71,
    trainer: "Sophie",
  },
  {
    id: 14,
    avatar: false,
    "first-name": "Sam",
    "last-name": "Vermeer",
    "start-date": "2025-02-13",
    "current-program": "Strength Basic",
    compliance: 84,
    trainer: "Mark",
  },
  {
    id: 15,
    avatar: false,
    "first-name": "Isa",
    "last-name": "Groen",
    "start-date": "2025-02-15",
    "current-program": "Rehab A",
    compliance: 85,
    trainer: "Lisa",
  },
];
