export const EXERCISES = [
  {
    id: 1,
    name: "bench press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "pectoralis minor",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 2,
    name: "deadlift",
    primaryMuscle: "erector spinae",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: [
      "quadriceps",
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "latissimus dorsi",
      "trapezius",
      "rhomboids",
      "forearm flexors",
      "obliques",
      "rectus abdominis",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 3,
    name: "overhead press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["triceps brachii", "deltoideus lateralis"],
    tertiaryMuscles: [
      "trapezius",
      "deltoideus posterior",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
      "obliques",
      "rectus abdominis",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 4,
    name: "barbell row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
      "erector spinae",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 5,
    name: "pull-up",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["biceps brachii", "teres major"],
    tertiaryMuscles: [
      "brachialis",
      "brachioradialis",
      "rhomboids",
      "trapezius",
      "deltoideus posterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
      "pectoralis minor",
    ],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "bodyweight",
  },
  {
    id: 6,
    name: "chin-up",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["biceps brachii", "brachialis"],
    tertiaryMuscles: [
      "brachioradialis",
      "teres major",
      "rhomboids",
      "trapezius",
      "deltoideus posterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
      "pectoralis minor",
    ],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "bodyweight",
  },
  {
    id: 7,
    name: "incline dumbbell press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "triceps brachii"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "pectoralis minor",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 8,
    name: "push-up",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "pectoralis minor",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
      "rectus abdominis",
      "obliques",
      "transversus abdominis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "bodyweight",
  },
  {
    id: 9,
    name: "dips",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["pectoralis major", "deltoideus anterior"],
    tertiaryMuscles: [
      "serratus anterior",
      "pectoralis minor",
      "latissimus dorsi",
      "trapezius",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
    ],
    movement: "vertical push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 10,
    name: "front squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: [
      "hamstrings",
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "rectus abdominis",
      "obliques",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 11,
    name: "back squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "adductors"],
    tertiaryMuscles: [
      "hamstrings",
      "erector spinae",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "rectus abdominis",
      "obliques",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 12,
    name: "bulgarian split squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "adductors"],
    tertiaryMuscles: [
      "hamstrings",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "erector spinae",
      "rectus abdominis",
      "obliques",
    ],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 4,
    equipmentCategory: "dumbbell",
  },
  {
    id: 13,
    name: "walking lunge",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "erector spinae",
      "rectus abdominis",
      "obliques",
    ],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "bodyweight",
  },
  {
    id: 14,
    name: "hip thrust",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "adductors"],
    tertiaryMuscles: [
      "erector spinae",
      "gluteus medius",
      "gluteus minimus",
      "quadriceps",
      "rectus abdominis",
      "obliques",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 15,
    name: "romanian deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "trapezius",
      "rhomboids",
      "latissimus dorsi",
      "forearm flexors",
      "rectus abdominis",
      "obliques",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 16,
    name: "sumo deadlift",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["adductors", "quadriceps"],
    tertiaryMuscles: [
      "hamstrings",
      "gluteus medius",
      "gluteus minimus",
      "erector spinae",
      "latissimus dorsi",
      "rhomboids",
      "trapezius",
      "forearm flexors",
      "rectus abdominis",
      "obliques",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 17,
    name: "good morning",
    primaryMuscle: "erector spinae",
    secondaryMuscles: ["hamstrings", "gluteus maximus"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "trapezius",
      "rhomboids",
      "latissimus dorsi",
      "rectus abdominis",
      "obliques",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 18,
    name: "seated cable row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "cable",
  },
  {
    id: 19,
    name: "face pull",
    primaryMuscle: "deltoideus posterior",
    secondaryMuscles: ["rhomboids", "trapezius"],
    tertiaryMuscles: [
      "infraspinatus",
      "teres minor",
      "supraspinatus",
      "deltoideus lateralis",
    ],
    movement: "horizontal pull",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 20,
    name: "lateral raise",
    primaryMuscle: "deltoideus lateralis",
    secondaryMuscles: ["supraspinatus", "trapezius"],
    tertiaryMuscles: [
      "deltoideus anterior",
      "deltoideus posterior",
      "serratus anterior",
    ],
    movement: "shoulder abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 21,
    name: "front raise",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["coracobrachialis", "supraspinatus"],
    tertiaryMuscles: [
      "serratus anterior",
      "trapezius",
      "deltoideus lateralis",
      "pectoralis minor",
    ],
    movement: "shoulder flexion",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 22,
    name: "rear delt fly",
    primaryMuscle: "deltoideus posterior",
    secondaryMuscles: ["rhomboids", "infraspinatus"],
    tertiaryMuscles: [
      "trapezius",
      "teres minor",
      "deltoideus lateralis",
      "erector spinae",
    ],
    movement: "horizontal abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 23,
    name: "arnold press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["deltoideus lateralis", "triceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "serratus anterior",
      "trapezius",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
      "obliques",
      "rectus abdominis",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 24,
    name: "bicep curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["supinator", "forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 25,
    name: "hammer curl",
    primaryMuscle: "brachioradialis",
    secondaryMuscles: ["brachialis", "biceps brachii"],
    tertiaryMuscles: ["forearm flexors", "supinator"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 26,
    name: "concentration curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["supinator", "forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 27,
    name: "preacher curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["supinator", "forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 28,
    name: "tricep pushdown",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["anconeus", "forearm extensors"],
    tertiaryMuscles: ["deltoideus anterior", "rotator cuff"],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 29,
    name: "skull crusher",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["anconeus", "deltoideus anterior"],
    tertiaryMuscles: ["rotator cuff", "forearm extensors"],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "barbell",
  },
  {
    id: 30,
    name: "overhead dumbbell tricep extension",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["anconeus", "deltoideus anterior"],
    tertiaryMuscles: [
      "trapezius",
      "serratus anterior",
      "rotator cuff",
      "forearm extensors",
    ],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 31,
    name: "cable tricep kickback",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["deltoideus posterior", "forearm extensors"],
    tertiaryMuscles: ["rotator cuff", "latissimus dorsi"],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 32,
    name: "leg press",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "adductors"],
    tertiaryMuscles: [
      "hamstrings",
      "soleus",
      "gastrocnemius",
      "gluteus medius",
      "gluteus minimus",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 4,
    equipmentCategory: "machine",
  },
  {
    id: 33,
    name: "leg extension",
    primaryMuscle: "quadriceps",
    secondaryMuscles: [],
    tertiaryMuscles: [],
    movement: "knee extension",
    bodyPart: "legs",
    primaryJoints: ["tibiofemoral"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 34,
    name: "leg curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gastrocnemius", "sartorius"],
    tertiaryMuscles: ["popliteus", "gracilis"],
    movement: "knee flexion",
    bodyPart: "legs",
    primaryJoints: ["tibiofemoral"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 35,
    name: "calf raise",
    primaryMuscle: "gastrocnemius",
    secondaryMuscles: ["soleus", "tibialis posterior"],
    tertiaryMuscles: [
      "flexor hallucis longus",
      "flexor digitorum longus",
      "peroneus longus",
      "peroneus brevis",
    ],
    movement: "plantar flexion",
    bodyPart: "calves",
    primaryJoints: ["talocrural"],
    systemicLoad: 1,
    equipmentCategory: "machine",
  },
  {
    id: 36,
    name: "seated calf raise",
    primaryMuscle: "soleus",
    secondaryMuscles: ["gastrocnemius", "tibialis posterior"],
    tertiaryMuscles: [
      "flexor hallucis longus",
      "flexor digitorum longus",
      "peroneus longus",
      "peroneus brevis",
    ],
    movement: "plantar flexion",
    bodyPart: "calves",
    primaryJoints: ["talocrural"],
    systemicLoad: 1,
    equipmentCategory: "machine",
  },
  {
    id: 37,
    name: "farmer's carry",
    primaryMuscle: "forearm flexors",
    secondaryMuscles: ["trapezius", "core musculature"],
    tertiaryMuscles: [
      "forearm extensors",
      "deltoideus lateralis",
      "deltoideus posterior",
      "erector spinae",
      "rectus abdominis",
      "obliques",
      "transversus abdominis",
      "gluteus medius",
      "gluteus minimus",
      "quadriceps",
      "hamstrings",
      "soleus",
      "gastrocnemius",
    ],
    movement: "carry",
    bodyPart: "full body",
    primaryJoints: [
      "coxofemoral",
      "tibiofemoral",
      "talocrural",
      "spine",
      "scapulothoracale",
    ],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 38,
    name: "shrug",
    primaryMuscle: "trapezius",
    secondaryMuscles: ["levator scapulae", "rhomboids"],
    tertiaryMuscles: [],
    movement: "scapular elevation",
    bodyPart: "traps",
    primaryJoints: ["scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 39,
    name: "barbell push press",
    primaryMuscle: "anterior deltoid",
    secondaryMuscles: ["triceps brachii", "upper trapezius"],
    tertiaryMuscles: [
      "quadriceps",
      "serratus anterior",
      "gluteus maximus",
      "gastrocnemius",
      "soleus",
      "erector spinae",
      "obliques",
      "rectus abdominis",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: [
      "glenohumeral",
      "humeroulnar",
      "coxofemoral",
      "tibiofemoral",
      "talocrural",
      "spine",
    ],
    systemicLoad: 4,
    equipmentCategory: "barbell",
    compoundLabel: "compound",
  },
  {
    id: 40,
    name: "pendlay row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
      "erector spinae",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "barbell",
  },
  {
    id: 41,
    name: "incline row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 42,
    name: "cable crossover",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "serratus anterior"],
    tertiaryMuscles: [
      "pectoralis minor",
      "deltoideus lateralis",
      "supraspinatus",
      "infraspinatus",
      "subscapularis",
      "teres minor",
    ],
    movement: "horizontal adduction",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "cable",
  },
  {
    id: 43,
    name: "pec deck",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "serratus anterior"],
    tertiaryMuscles: [
      "pectoralis minor",
      "supraspinatus",
      "infraspinatus",
      "subscapularis",
      "teres minor",
    ],
    movement: "horizontal adduction",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 44,
    name: "cable chest fly",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "serratus anterior"],
    tertiaryMuscles: [
      "pectoralis minor",
      "supraspinatus",
      "infraspinatus",
      "subscapularis",
      "teres minor",
    ],
    movement: "horizontal adduction",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 45,
    name: "cable lateral raise",
    primaryMuscle: "deltoideus lateralis",
    secondaryMuscles: ["supraspinatus", "trapezius"],
    tertiaryMuscles: [
      "deltoideus anterior",
      "deltoideus posterior",
      "serratus anterior",
    ],
    movement: "shoulder abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 46,
    name: "hanging leg raise",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["iliopsoas", "rectus femoris"],
    tertiaryMuscles: [
      "hip flexors",
      "tensor fasciae latae",
      "pectineus",
      "obliques",
      "transversus abdominis",
    ],
    movement: "hip flexion",
    bodyPart: "core",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 47,
    name: "plank",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["transversus abdominis", "obliques"],
    tertiaryMuscles: [
      "gluteus maximus",
      "erector spinae",
      "serratus anterior",
      "deltoideus anterior",
    ],
    movement: "anti-extension",
    bodyPart: "core",
    primaryJoints: ["glenohumeral", "coxofemoral", "spine"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 48,
    name: "russian twist",
    primaryMuscle: "obliques",
    secondaryMuscles: ["rectus abdominis", "transversus abdominis"],
    tertiaryMuscles: ["quadratus lumborum", "erector spinae", "hip flexors"],
    movement: "trunk rotation",
    bodyPart: "core",
    primaryJoints: ["spine"],
    systemicLoad: 1,
    equipmentCategory: "other",
  },
  {
    id: 49,
    name: "cable woodchopper",
    primaryMuscle: "obliques",
    secondaryMuscles: ["rectus abdominis", "latissimus dorsi"],
    tertiaryMuscles: [
      "transversus abdominis",
      "erector spinae",
      "gluteus medius",
      "serratus anterior",
      "deltoideus anterior",
    ],
    movement: "trunk rotation",
    bodyPart: "core",
    primaryJoints: ["glenohumeral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "cable",
  },
  {
    id: 50,
    name: "ab wheel rollout",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["transversus abdominis", "serratus anterior"],
    tertiaryMuscles: [
      "hip flexors",
      "obliques",
      "latissimus dorsi",
      "deltoideus anterior",
      "erector spinae",
    ],
    movement: "anti-extension",
    bodyPart: "core",
    primaryJoints: ["glenohumeral", "coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "other",
  },
  {
    id: 51,
    name: "zercher squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: [
      "hamstrings",
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "rectus abdominis",
      "obliques",
      "biceps brachii",
      "forearm flexors",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 52,
    name: "landmine press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["triceps brachii", "pectoralis major"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "serratus anterior",
      "trapezius",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "obliques",
      "rectus abdominis",
    ],
    movement: "angled press",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "other",
  },
  {
    id: 53,
    name: "landmine row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
      "erector spinae",
      "obliques",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 54,
    name: "hip abduction machine",
    primaryMuscle: "gluteus medius",
    secondaryMuscles: ["gluteus minimus", "tensor fasciae latae"],
    tertiaryMuscles: ["gluteus maximus", "piriformis"],
    movement: "hip abduction",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 55,
    name: "hip adduction machine",
    primaryMuscle: "adductors",
    secondaryMuscles: ["adductor magnus", "adductor longus"],
    tertiaryMuscles: ["pectineus", "adductor brevis", "gracilis"],
    movement: "hip adduction",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral"],
    systemicLoad: 1,
    equipmentCategory: "machine",
  },
  {
    id: 56,
    name: "incline bench press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "triceps brachii"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "pectoralis minor",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 57,
    name: "decline bench press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["deltoideus anterior", "triceps brachii"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "pectoralis minor",
      "serratus anterior",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
      "subscapularis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 58,
    name: "chest supported row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
      "infraspinatus",
      "teres minor",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 59,
    name: "machine shoulder press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["triceps brachii", "deltoideus lateralis"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "serratus anterior",
      "trapezius",
      "supraspinatus",
      "infraspinatus",
      "teres minor",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 60,
    name: "machine chest press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "deltoideus lateralis",
      "serratus anterior",
      "pectoralis minor",
      "supraspinatus",
      "infraspinatus",
      "subscapularis",
      "teres minor",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 61,
    name: "reverse lunge",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "erector spinae",
      "rectus abdominis",
      "obliques",
    ],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "bodyweight",
  },
  {
    id: 62,
    name: "step-up",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
      "gastrocnemius",
      "erector spinae",
      "rectus abdominis",
      "obliques",
    ],
    movement: "step-up",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "bodyweight",
  },
  {
    id: 63,
    name: "nordic hamstring curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gastrocnemius", "sartorius"],
    tertiaryMuscles: ["gracilis", "popliteus"],
    movement: "knee flexion",
    bodyPart: "legs",
    primaryJoints: ["tibiofemoral"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 64,
    name: "glute kickback",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "adductor magnus"],
    tertiaryMuscles: ["gluteus medius", "erector spinae"],
    movement: "hip extension",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral"],
    systemicLoad: 1,
    equipmentCategory: "other",
  },
  {
    id: 65,
    name: "donkey calf raise",
    primaryMuscle: "gastrocnemius",
    secondaryMuscles: ["soleus", "tibialis posterior"],
    tertiaryMuscles: [
      "flexor hallucis longus",
      "flexor digitorum longus",
      "peroneus longus",
      "peroneus brevis",
    ],
    movement: "plantar flexion",
    bodyPart: "calves",
    primaryJoints: ["talocrural"],
    systemicLoad: 1,
    equipmentCategory: "machine",
  },
  {
    id: 66,
    name: "front plate raise",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["coracobrachialis", "supraspinatus"],
    tertiaryMuscles: ["serratus anterior", "trapezius", "deltoideus lateralis"],
    movement: "shoulder flexion",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "other",
  },
  {
    id: 67,
    name: "zottman curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachioradialis", "brachialis"],
    tertiaryMuscles: ["forearm extensors", "supinator", "pronator teres"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 68,
    name: "reverse curl",
    primaryMuscle: "brachioradialis",
    secondaryMuscles: ["brachialis", "forearm extensors"],
    tertiaryMuscles: ["biceps brachii", "pronator teres"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 69,
    name: "overhead rope face pull",
    primaryMuscle: "deltoideus posterior",
    secondaryMuscles: ["rhomboids", "infraspinatus"],
    tertiaryMuscles: [
      "trapezius",
      "teres minor",
      "supraspinatus",
      "deltoideus lateralis",
      "serratus anterior",
    ],
    movement: "horizontal pull",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 70,
    name: "swiss ball crunch",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["obliques", "transversus abdominis"],
    tertiaryMuscles: ["hip flexors", "iliopsoas", "rectus femoris"],
    movement: "spinal flexion",
    bodyPart: "core",
    primaryJoints: ["spine"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 71,
    name: "close-grip bench press",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["pectoralis major", "deltoideus anterior"],
    tertiaryMuscles: ["anconeus", "serratus anterior", "pectoralis minor"],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 3,
    equipmentCategory: "barbell",
  },
  {
    id: 72,
    name: "dumbbell floor press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: ["serratus anterior", "pectoralis minor"],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 73,
    name: "decline push-up",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "serratus anterior",
      "pectoralis minor",
      "deltoideus lateralis",
      "rectus abdominis",
      "obliques",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 74,
    name: "ring push-up",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "serratus anterior",
      "pectoralis minor",
      "rotator cuff",
      "rectus abdominis",
      "obliques",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 75,
    name: "one-arm dumbbell bench press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "deltoideus anterior"],
    tertiaryMuscles: [
      "serratus anterior",
      "pectoralis minor",
      "obliques",
      "transversus abdominis",
    ],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 76,
    name: "goblet squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: ["adductors", "hamstrings", "rectus abdominis"],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 77,
    name: "hack squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "adductors"],
    tertiaryMuscles: [
      "hamstrings",
      "erector spinae",
      "soleus",
      "gastrocnemius",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 4,
    equipmentCategory: "machine",
  },
  {
    id: 78,
    name: "box squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: [
      "hamstrings",
      "adductors",
      "rectus abdominis",
      "obliques",
    ],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "barbell",
  },
  {
    id: 79,
    name: "split squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: [
      "adductors",
      "gluteus medius",
      "gluteus minimus",
      "soleus",
    ],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 80,
    name: "lateral lunge",
    primaryMuscle: "gluteus medius",
    secondaryMuscles: ["quadriceps", "gluteus maximus"],
    tertiaryMuscles: ["adductors", "hamstrings", "gluteus minimus"],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 81,
    name: "stiff-leg deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: ["adductors", "gastrocnemius"],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 82,
    name: "back extension",
    primaryMuscle: "erector spinae",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: ["gluteus medius", "adductors"],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 83,
    name: "reverse hyperextension",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "erector spinae"],
    tertiaryMuscles: ["gluteus medius", "adductor magnus"],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 84,
    name: "kettlebell swing",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "erector spinae"],
    tertiaryMuscles: ["quadriceps", "gluteus medius", "forearm flexors"],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 85,
    name: "lat pulldown",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["biceps brachii", "teres major"],
    tertiaryMuscles: [
      "rhomboids",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "deltoideus posterior",
    ],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 86,
    name: "wide-grip pulldown",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["teres major", "biceps brachii"],
    tertiaryMuscles: [
      "rhomboids",
      "trapezius",
      "brachialis",
      "brachioradialis",
    ],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 87,
    name: "neutral-grip pulldown",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["brachialis", "biceps brachii"],
    tertiaryMuscles: [
      "teres major",
      "rhomboids",
      "trapezius",
      "brachioradialis",
    ],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "machine",
  },
  {
    id: 88,
    name: "one-arm dumbbell row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
      "teres major",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 89,
    name: "t-bar row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "teres major",
      "erector spinae",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 3,
    equipmentCategory: "other",
  },
  {
    id: 90,
    name: "inverted row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "biceps brachii"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "brachialis",
      "brachioradialis",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 91,
    name: "push press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["triceps brachii", "deltoideus lateralis"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "trapezius",
      "serratus anterior",
      "rectus abdominis",
      "obliques",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: [
      "glenohumeral",
      "humeroulnar",
      "tibiofemoral",
      "coxofemoral",
    ],
    systemicLoad: 4,
    equipmentCategory: "barbell",
  },
  {
    id: 92,
    name: "seated dumbbell shoulder press",
    primaryMuscle: "deltoideus anterior",
    secondaryMuscles: ["triceps brachii", "deltoideus lateralis"],
    tertiaryMuscles: [
      "deltoideus posterior",
      "serratus anterior",
      "trapezius",
      "supraspinatus",
    ],
    movement: "vertical push",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 93,
    name: "upright row",
    primaryMuscle: "deltoideus lateralis",
    secondaryMuscles: ["trapezius", "biceps brachii"],
    tertiaryMuscles: ["deltoideus anterior", "supraspinatus"],
    movement: "shoulder abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "humeroulnar", "scapulothoracale"],
    systemicLoad: 2,
    equipmentCategory: "barbell",
  },
  {
    id: 94,
    name: "single-arm cable lateral raise",
    primaryMuscle: "deltoideus lateralis",
    secondaryMuscles: ["supraspinatus", "trapezius"],
    tertiaryMuscles: ["deltoideus anterior", "deltoideus posterior"],
    movement: "shoulder abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracale"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 95,
    name: "incline dumbbell curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["supinator", "forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 96,
    name: "ez-bar curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["supinator", "forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "barbell",
  },
  {
    id: 97,
    name: "rope hammer curl",
    primaryMuscle: "brachioradialis",
    secondaryMuscles: ["brachialis", "biceps brachii"],
    tertiaryMuscles: ["forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 98,
    name: "overhead cable tricep extension",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["anconeus", "deltoideus anterior"],
    tertiaryMuscles: ["rotator cuff", "forearm extensors", "serratus anterior"],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 99,
    name: "crunch",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["obliques", "transversus abdominis"],
    tertiaryMuscles: ["hip flexors"],
    movement: "spinal flexion",
    bodyPart: "core",
    primaryJoints: ["spine"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 100,
    name: "hanging knee raise",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["iliopsoas", "rectus femoris"],
    tertiaryMuscles: [
      "obliques",
      "transversus abdominis",
      "tensor fasciae latae",
      "pectineus",
    ],
    movement: "hip flexion",
    bodyPart: "core",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 101,
    name: "side plank",
    primaryMuscle: "obliques",
    secondaryMuscles: ["transversus abdominis", "rectus abdominis"],
    tertiaryMuscles: ["quadratus lumborum", "gluteus medius", "deltoideus"],
    movement: "core stabilization",
    bodyPart: "core",
    primaryJoints: ["spine", "coxofemoral", "glenohumeral"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 102,
    name: "pallof press",
    primaryMuscle: "obliques",
    secondaryMuscles: ["rectus abdominis", "transversus abdominis"],
    tertiaryMuscles: ["erector spinae", "gluteus medius", "deltoideus"],
    movement: "core anti-rotation",
    bodyPart: "core",
    primaryJoints: ["spine", "coxofemoral", "glenohumeral"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 103,
    name: "side bend",
    primaryMuscle: "obliques",
    secondaryMuscles: ["rectus abdominis"],
    tertiaryMuscles: ["quadratus lumborum", "erector spinae"],
    movement: "spinal lateral flexion",
    bodyPart: "core",
    primaryJoints: ["spine"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 104,
    name: "v-up",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["iliopsoas", "rectus femoris"],
    tertiaryMuscles: [
      "obliques",
      "transversus abdominis",
      "tensor fasciae latae",
    ],
    movement: "hip flexion + spinal flexion",
    bodyPart: "core",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 105,
    name: "suitcase carry",
    primaryMuscle: "obliques",
    secondaryMuscles: ["transversus abdominis", "rectus abdominis"],
    tertiaryMuscles: [
      "quadratus lumborum",
      "erector spinae",
      "gluteus medius",
      "forearm flexors",
    ],
    movement: "core anti-lateral flexion",
    bodyPart: "core",
    primaryJoints: ["spine", "coxofemoral", "glenohumeral"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 106,
    name: "sit-up",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["iliopsoas", "rectus femoris"],
    tertiaryMuscles: [
      "obliques",
      "transversus abdominis",
      "tensor fasciae latae",
      "adductor longus",
    ],
    movement: "spinal flexion + hip flexion",
    bodyPart: "core",
    primaryJoints: ["spine", "coxofemoral"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 107,
    name: "booty builder",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "adductors"],
    tertiaryMuscles: [
      "erector spinae",
      "gluteus medius",
      "gluteus minimus",
      "quadriceps",
      "rectus abdominis",
      "obliques",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 3,
    equipmentCategory: "barbell",
  },
  {
    id: 108,
    name: "cable pull-through",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "erector spinae"],
    tertiaryMuscles: ["adductor magnus", "gluteus medius"],
    movement: "hip extension",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "cable",
  },
  {
    id: 109,
    name: "sissy squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["hip flexors"],
    tertiaryMuscles: ["rectus abdominis", "tibialis anterior"],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["tibiofemoral", "coxofemoral", "talocrural"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 110,
    name: "single-leg romanian deadlift",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: [
      "gluteus medius",
      "gluteus minimus",
      "adductors",
      "quadratus lumborum",
    ],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell",
  },
  {
    id: 111,
    name: "glute-ham raise",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: ["gastrocnemius", "adductors"],
    movement: "hip hinge",
    bodyPart: "hips",
    primaryJoints: ["tibiofemoral", "coxofemoral", "spine"],
    systemicLoad: 3,
    equipmentCategory: "machine",
  },
  {
    id: 112,
    name: "belt squat",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: ["adductors", "calves"],
    movement: "squat",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "machine",
  },
  {
    id: 113,
    name: "sled push",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: ["calves", "erector spinae", "adductors", "core"],
    movement: "knee extension",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural", "spine"],
    systemicLoad: 5,
    equipmentCategory: "sled",
  },
  {
    id: 114,
    name: "single-leg hip thrust",
    primaryMuscle: "gluteus maximus",
    secondaryMuscles: ["hamstrings", "erector spinae"],
    tertiaryMuscles: ["gluteus medius", "adductors", "core"],
    movement: "hip extension",
    bodyPart: "hips",
    primaryJoints: ["coxofemoral", "spine"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight",
  },
  {
    id: 115,
    name: "lat prayer",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["teres major", "trapezius"],
    tertiaryMuscles: ["rhomboids", "posterior deltoid", "triceps brachii"],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 116,
    name: "single-arm seated cable row",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["rhomboids", "posterior deltoid"],
    tertiaryMuscles: ["trapezius", "biceps brachii", "brachialis"],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "scapulothoracic", "humeroulnar"],
    systemicLoad: 2,
    equipmentCategory: "cable",
  },
  {
    id: 117,
    name: "dumbbell butterfly",
    primaryMuscle: "deltoideus posterior",
    secondaryMuscles: ["deltoideus lateralis"],
    tertiaryMuscles: ["rhomboids", "trapezius", "infraspinatus", "teres minor"],
    movement: "horizontal abduction",
    bodyPart: "shoulders",
    primaryJoints: ["glenohumeral", "scapulothoracic"],
    systemicLoad: 1,
    equipmentCategory: "dumbbell",
  },
  {
    id: 118,
    name: "single-leg leg press",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: ["adductors", "calves"],
    movement: "knee extension + hip extension",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "machine",
  },
  {
    id: 119,
    name: "dumbbell pullover",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["pectoralis major", "triceps brachii"],
    tertiaryMuscles: ["serratus anterior", "rhomboids"],
    movement: "vertical pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral"],
    systemicLoad: 2,
    equipmentCategory: "dumbbell",
  },
  {
    id: 120,
    name: "seated cable chest press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["triceps brachii", "anterior deltoid"],
    tertiaryMuscles: ["serratus anterior", "biceps brachii (short head)"],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 3,
    equipmentCategory: "cable",
  },
  {
    id: 121,
    name: "neutral-grip lat pulldown",
    primaryMuscle: "latissimus dorsi",
    secondaryMuscles: ["teres major", "biceps brachii"],
    tertiaryMuscles: [
      "brachialis",
      "rhomboids",
      "trapezius",
      "posterior deltoid",
    ],
    movement: "horizontal pull",
    bodyPart: "back",
    primaryJoints: ["glenohumeral", "scapulothoracic", "humeroulnar"],
    systemicLoad: 3,
    equipmentCategory: "cable/machine",
  },
  {
    id: 122,
    name: "front foot elevated reverse lunge",
    primaryMuscle: "quadriceps",
    secondaryMuscles: ["gluteus maximus", "hamstrings"],
    tertiaryMuscles: ["adductors", "calves", "core"],
    movement: "lunge",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral", "talocrural"],
    systemicLoad: 3,
    equipmentCategory: "dumbbell/barbell/bodyweight",
  },
  {
    id: 123,
    name: "bayesian curl",
    primaryMuscle: "biceps brachii",
    secondaryMuscles: ["brachialis", "brachioradialis"],
    tertiaryMuscles: ["forearm flexors"],
    movement: "elbow flexion",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 124,
    name: "cross-body cable extension",
    primaryMuscle: "triceps brachii",
    secondaryMuscles: ["forearm extensors"],
    tertiaryMuscles: [],
    movement: "elbow extension",
    bodyPart: "arms",
    primaryJoints: ["humeroulnar"],
    systemicLoad: 1,
    equipmentCategory: "cable",
  },
  {
    id: 125,
    name: "dead bug",
    primaryMuscle: "rectus abdominis",
    secondaryMuscles: ["obliquus internus", "obliquus externus"],
    tertiaryMuscles: [
      "transversus abdominis",
      "hip flexors",
      "spinal stabilizers",
    ],
    movement: "spinal stabilization",
    bodyPart: "core",
    primaryJoints: ["spine", "coxofemoral", "glenohumeral"],
    systemicLoad: 1,
    equipmentCategory: "bodyweight",
  },
  {
    id: 126,
    name: "glider leg curl",
    primaryMuscle: "hamstrings",
    secondaryMuscles: ["gluteus maximus", "erector spinae"],
    tertiaryMuscles: ["core stabilizers", "gastrocnemius"],
    movement: "knee flexion",
    bodyPart: "legs",
    primaryJoints: ["coxofemoral", "tibiofemoral"],
    systemicLoad: 2,
    equipmentCategory: "bodyweight / sliders",
  },
  {
    id: 127,
    name: "seated cable chest press",
    primaryMuscle: "pectoralis major",
    secondaryMuscles: ["anterior deltoid", "triceps brachii"],
    tertiaryMuscles: ["serratus anterior", "core stabilizers"],
    movement: "horizontal push",
    bodyPart: "chest",
    primaryJoints: ["glenohumeral", "humeroulnar"],
    systemicLoad: 2,
    equipmentCategory: "cable machine",
  },
];
