export const PROGRAMS = [
  {
    id: 1,
    dateCreated: "2023-02-14",
    programName: "Strength Foundation",
    duration: 8,
    workoutsPerWeek: 3,
    activeClients: 25,
    completed: 42,
    compliance: 86,
  },
  {
    id: 2,
    dateCreated: "2022-09-03",
    programName: "Hypertrophy Builder",
    duration: 12,
    workoutsPerWeek: 4,
    activeClients: 18,
    completed: 27,
    compliance: 78,
  },
  {
    id: 3,
    dateCreated: "2024-01-22",
    programName: "Endurance Boost",
    duration: 10,
    workoutsPerWeek: 5,
    activeClients: 12,
    completed: 15,
    compliance: 91,
  },
  {
    id: 4,
    dateCreated: "2023-06-10",
    programName: "Rehab & Mobility",
    duration: 6,
    workoutsPerWeek: 2,
    activeClients: 30,
    completed: 65,
    compliance: 88,
  },
  {
    id: 5,
    dateCreated: "2022-11-18",
    programName: "Fat Loss Accelerator",
    duration: 16,
    workoutsPerWeek: 4,
    activeClients: 22,
    completed: 34,
    compliance: 73,
  },
  {
    id: 6,
    dateCreated: "2023-03-27",
    programName: "Power & Performance",
    duration: 12,
    workoutsPerWeek: 5,
    activeClients: 14,
    completed: 19,
    compliance: 84,
  },
  {
    id: 7,
    dateCreated: "2024-05-09",
    programName: "Beginner Bootcamp",
    duration: 6,
    workoutsPerWeek: 3,
    activeClients: 40,
    completed: 92,
    compliance: 89,
  },
  {
    id: 8,
    dateCreated: "2023-08-15",
    programName: "Functional Fitness",
    duration: 10,
    workoutsPerWeek: 4,
    activeClients: 17,
    completed: 23,
    compliance: 81,
  },
  {
    id: 9,
    dateCreated: "2022-12-04",
    programName: "Athlete Conditioning",
    duration: 14,
    workoutsPerWeek: 6,
    activeClients: 10,
    completed: 12,
    compliance: 95,
  },
  {
    id: 10,
    dateCreated: "2024-04-02",
    programName: "Posture Reset",
    duration: 8,
    workoutsPerWeek: 2,
    activeClients: 28,
    completed: 46,
    compliance: 87,
  },
  {
    id: 11,
    dateCreated: "2023-09-29",
    programName: "Core Strength Pro",
    duration: 12,
    workoutsPerWeek: 3,
    activeClients: 15,
    completed: 22,
    compliance: 82,
  },
  {
    id: 12,
    dateCreated: "2024-02-11",
    programName: "Speed & Agility",
    duration: 8,
    workoutsPerWeek: 4,
    activeClients: 9,
    completed: 11,
    compliance: 90,
  },
];
