export const WORKOUTS = [
  {
    id: 0,
    name: "Full-Body A",
    type: "Strength",
    exercises: 8,
    programs: 2,
    assignedTo: ["Emma Jansen", "Lars de Vries"],
  },
  {
    id: 1,
    name: "Full-Body B",
    type: "Strength",
    exercises: 8,
    programs: 1,
    assignedTo: ["Sanne Visser"],
  },
  {
    id: 2,
    name: "Upper Body Push",
    type: "Hypertrophy",
    exercises: 10,
    programs: 3,
    assignedTo: ["Milan de Boer", "Noa van Dijk"],
  },
  {
    id: 3,
    name: "Upper Body Pull",
    type: "Hypertrophy",
    exercises: 10,
    programs: 2,
    assignedTo: ["Femke Smit"],
  },
  {
    id: 4,
    name: "Lower Body Strength",
    type: "Strength",
    exercises: 9,
    programs: 2,
    assignedTo: ["Daan Bakker", "Iris Willems"],
  },
  {
    id: 5,
    name: "Leg Day Volume",
    type: "Hypertrophy",
    exercises: 12,
    programs: 1,
    assignedTo: ["Tom Mulder"],
  },
  {
    id: 6,
    name: "Core & Stability",
    type: "Core",
    exercises: 7,
    programs: 2,
    assignedTo: ["Eva Kuipers", "Ruben Meijer"],
  },
  {
    id: 7,
    name: "HIIT Sprints",
    type: "HIIT",
    exercises: 6,
    programs: 1,
    assignedTo: ["Nina Vos"],
  },
  {
    id: 8,
    name: "Mobility Flow",
    type: "Mobility",
    exercises: 8,
    programs: 1,
    assignedTo: ["Jesse de Graaf"],
  },
  {
    id: 9,
    name: "Rehab: Shoulder",
    type: "Rehab",
    exercises: 6,
    programs: 2,
    assignedTo: ["Loïs van Dam", "Koen Vermeer"],
  },
  {
    id: 10,
    name: "Rehab: Knee",
    type: "Rehab",
    exercises: 6,
    programs: 2,
    assignedTo: ["Laura Peeters"],
  },
  {
    id: 11,
    name: "Endurance Tempo Run",
    type: "Endurance",
    exercises: 5,
    programs: 1,
    assignedTo: ["Tim van Leeuwen"],
  },
  {
    id: 12,
    name: "Power & Plyometrics",
    type: "Power",
    exercises: 9,
    programs: 2,
    assignedTo: ["Emma Jansen"],
  },
  {
    id: 13,
    name: "Chest & Triceps",
    type: "Hypertrophy",
    exercises: 10,
    programs: 3,
    assignedTo: ["Lars de Vries", "Noa van Dijk"],
  },
  {
    id: 14,
    name: "Back & Biceps",
    type: "Hypertrophy",
    exercises: 10,
    programs: 3,
    assignedTo: ["Ruben Meijer"],
  },
  {
    id: 15,
    name: "Glute Builder",
    type: "Strength",
    exercises: 9,
    programs: 2,
    assignedTo: ["Femke Smit"],
  },
];
